# -*- coding: utf-8 -*-
"""AnalisadorDeAnoBissexto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKoxfPTQUgunmueveoY3x-eERFSGcV8j
"""

print('-°-'*40)
print('ANALISADOR DE TRIÂNGULOS:')
print('-°-'*40)
a = float(input('\033[1;33mPrimeiro segmento: \033[m'))
b = float(input('\033[1;33mSegundo segmento: \033[1;33m'))
c = float(input('\033[1;33mTerceiro segmento: \033[1;33m'))
if (b - c) < a < b + c and (c - a) < b < c + a and (a - b) < c < b + a:
    print('\033[1;32mOs segmentos acima PODEM FORMAR um triângulo!\033[m')
else:
    print('\033[1;31mOs segmentos acima NÃO PODEM FORMAR um triângulo!\033[m')